apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.1-devel
      command:
      - sleep
      - "3600"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs

